- name: "Install MySQL"
  apt: pkg={{ item }} state=latest
  notify: Restart MySQL
  with_items:
   - mysql-server
   - python-mysqldb

- name: set mysql root password
  mysql_user: >
      name=root
      host={{ item }}
      password={{ mysql_root_password|mandatory }}
      priv=*.*:ALL,GRANT
  with_items:
   - "{{ ansible_hostname }}"
   - "mysql.service.consul"
   - "127.0.0.1"
   - "::1"
   - "localhost"

- name: Generate .my.cnf file with root password credentials
  template: src=dotmy.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Configure MySQL
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify: Restart MySQL

- name: Create MySQL User for each Database/Hosts combination
  mysql_user: >
    host={{ item[1] }}
    name={{ item[0].name|default(item[0].app) }}
    password={{ item[0].password }}
    priv={{ item[0].database|default(item[0].app) }}.*:ALL state=present
    login_password={{ mysql_root_password }}
    login_user=root
  with_nested:
    - mysql_databases 
    - mysql_allowed_hosts

- name: Create Databases
  mysql_db: >
    name={{ item.database|default(item.name) }}
    state=present
    collation={{ item.collation|default('utf8_general_ci') }}
    encoding={{ item.encoding|default('utf8') }}
    login_host=localhost
    login_user=root
    login_password={{ mysql_root_password }}
  with_items: mysql_databases

- name: Register Consul Service
  template: src=consul.j2 dest=/etc/consul.d/mysql.json

- name: Register Consul KV Configuration
  command:
      curl -d"mysql://{{ item.name|default(item.app) }}:{{ item.password }}@{{ item.name|default(item.app) }}.mysql.service.consul:{{ mysql_port }}/{{ item.database|default(item.app) }}" -XPUT "http://localhost:8500/v1/kv/apps/{{ item.app }}/mysql/connection/{{ item.name }}"
  with_items: mysql_databases

- name: Reload Consul
  command: consul reload
