- name: "Install MySQL"
  apt: pkg={{ item }} state=latest
  notify: Restart MySQL
  with_items:
   - mysql-server
   - python-mysqldb
  when: "'mysql' in group_names"

- name: set mysql root password
  mysql_user: >
      name=root
      host={{ item }}
      password={{ mysql_root_password|mandatory }}
      priv=*.*:ALL,GRANT
  when: "'mysql' in group_names"
  with_items:
   - "{{ ansible_hostname }}"
   - "127.0.0.1"
   - "::1"
   - "localhost"

- name: Generate .my.cnf file with root password credentials
  template: src=dotmy.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  when: "'mysql' in group_names"

- name: Configure MySQL
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify: Restart MySQL
  when: "'mysql' in group_names"

- name: Create MySQL User for each Database/Hosts combination
  mysql_user: >
    host={{ item[1] }}
    name={{ item[0].name }}
    password={{ item[0].password }}
    priv={{ item[0].name }}.*:ALL state=present
    login_password={{ mysql_root_password }}
    login_user=root
  when: "'mysql' in group_names"
  with_nested:
    - mysql_databases 
    - mysql_allowed_hosts

- name: Create Databases
  mysql_db: >
    name={{ item.name }}
    state=present
    collation={{ item.collation|default('utf8_general_ci') }}
    encoding={{ item.encoding|default('utf8') }}
    login_host=localhost
    login_user=root
    login_password={{ mysql_root_password }}
  with_items: mysql_databases
  when: "'mysql' in group_names"
